[build]
  functions = "netlify/functions"

[[redirects]]
  from = "http://5iles.com/*"
  to = "https://5iles.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.5iles.com/*"
  to = "https://5iles.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
